# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 
  vmImage: windows-latest

stages:
  - stage: deploy
    displayName: deploy Azure Vm
    
    jobs:
      - deployment: deploy_Azure_Vm
        displayName: 'Deploy bicep to Azure'
        environment: 'testAzureDeployment'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'AzDo-Connection'
                    scriptType: 'pscore'
                    scriptLocation: 'inlineScript'
                    inlineScript: 'az login -u xchy1427256@163.com -p Xchhhhhy@1998'
                - task: AzureCLI@2
                  displayName: show group info
                  inputs:
                    azureSubscription: 'AzDo-Connection'
                    scriptType: 'pscore'
                    scriptLocation: 'inlineScript'
                    inlineScript: 'az group list'
                
