# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
  - stage: deploy
    displayName: deploy Azure Vm
    pool: 
      vmImage: windows-latest
    jobs:
      - deployment: deploy-Azure-Vm
        displayName: deploy Azure VM
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzurePowerShell@5
                  inputs:
                    azureSubscription: 'az devops connection'
                    ScriptType: 'InlineScript'
                    Inline: 'New-AzResourceGroup -Name testRG -Location EastUS'
                    azurePowerShellVersion: 'LatestVersion'
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'az devops connection'
                    scriptType: 'ps'
                    scriptLocation: 'inlineScript'
                    inlineScript: 'az bicep build --file .\bicep\main.bicep'
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'az devops connection'
                    scriptType: 'ps'
                    scriptLocation: 'inlineScript'
                    inlineScript: 'az deployment group create --template-file .\bicep\main.bicep --parameters .\bicep\params\main.parameters.json --resource-group testRG'
'

