# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: DotNetCoreCLI@2
  displayName: 'build project'
  inputs:
    command: 'build'
    projects: './test.csproj'
    arguments: '--no-restore --configuration Release'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 

- task: Npm@1
  inputs:
    command: 'ci'
