# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 
  vmImage: windows-latest

stages:
  - stage: deploy
    displayName: deploy Azure Vm
    
    jobs:
      - deployment: deploy_Azure_Vm
        displayName: deploy Azure VM
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzurePowerShell@5
                  inputs:
                    azureSubscription: 'az devops connection'
                    ScriptType: 'InlineScript'
                    Inline: 'New-AzResourceGroup -Name testRG -Location EastUS'
                    azurePowerShellVersion: 'LatestVersion'
                - task: AzurePowerShell@5
                  inputs:
                    azureSubscription: 'az devops connection'
                    ScriptType: 'InlineScript'
                    Inline: 'az bicep build --file .\bicep\main.bicep'
                    azurePowerShellVersion: 'LatestVersion'
                - task: AzurePowerShell@5
                  inputs:
                    azureSubscription: 'az devops connection'
                    ScriptType: 'InlineScript'
                    Inline: 'az deployment group create --template-file .\bicep\main.bicep --parameters .\bicep\params\main.parameters.json --resource-group testRG'
                    azurePowerShellVersion: 'LatestVersion'
