# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

stages:
  - stage: build
    jobs:
    - job: build
      steps:
      - task: InstallShieldBuild@1
        inputs:
          PrjName: 'F:\Perforce\idk_installation\V12.2\INT\MVA\Unscrambler HSI\Unscrambler HSI.ism'
          Parameters: '-v'
          AgentLoc: 'PrivateAgent'
          SABPath: 'G:\InstallShield'
