# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 
  vmImage: windows-latest

variables:
  rgName: 'newRG'

stages:
  - stage: deploy
    displayName: deploy Azure Vm
    
    jobs:
      - deployment: deploy_Azure_Vm
        displayName: 'Deploy bicep to Azure'
        environment: 'testAzureDeployment'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: crate resource group
                  inputs:
                    azureSubscription: 'AzDo-Connection'
                    scriptType: 'pscore'
                    scriptLocation: 'inlineScript'
                    inlineScript: 'az group create --name $(rgName) --location eastus'
                - task: AzureCLI@2
                  displayName: build bicep
                  inputs:
                    azureSubscription: 'AzDo-Connection'
                    scriptType: 'pscore'
                    scriptLocation: 'inlineScript'
                    inlineScript: 'az bicep build --file $(Build.SourcesDirectory)/main.bicep'
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'AzDo-Connection'
                    scriptType: 'pscore'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az deployment group create --template-file 
                      $(Build.SourcesDirectory)/main.bicep --parameters 
                      $(Build.SourcesDirectory)/params/main.parameters.json --resource-group $(rgName)
                
