# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master

pool: 
  vmImage: windows-latest

variables:
  rgName: 'newRG'

stages:
  - stage: deploy
    displayName: deploy Azure Vm
    
    jobs:
      - deployment: deploy_Azure_Vm
        environment: 'testAzureDeployment'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: CmdLine@2
                  displayName: clone git repo
                  inputs:
                    script: |
                      git clone https://github.com/xiangchengyu/build-pipeline.git
                    workingDirectory: '$(Build.SourcesDirectory)'
                - task: AzureCLI@2
                  displayName: create resource group
                  inputs:
                    azureSubscription: 'AzDo-Connection'
                    scriptType: 'pscore'
                    scriptLocation: 'inlineScript'
                    inlineScript: 'az group create --name $(rgName) --location eastus'
                - task: AzureCLI@2
                  displayName: build bicep
                  inputs:
                    azureSubscription: 'AzDo-Connection'
                    scriptType: 'pscore'
                    scriptLocation: 'inlineScript'
                    inlineScript: 'az bicep build --file $(Build.SourcesDirectory)/build-pipeline/main.bicep'
                - task: AzureCLI@2
                  displayName: deploy bicep
                  inputs:
                    azureSubscription: 'AzDo-Connection'
                    scriptType: 'pscore'
                    scriptLocation: 'inlineScript'
                    inlineScript: 'az deployment group create --template-file $(Build.SourcesDirectory)/build-pipeline/main.bicep --parameters $(Build.SourcesDirectory)/build-pipeline/params/main.parameters.json --resource-group $(rgName)'
                
